# Generated by Django 5.2.14 on 2026-05-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gcash_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gcash_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
