# Generated by Django 5.2.14 on 2026-05-27 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_userprofile_gcash_name_userprofile_gcash_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.FileField(blank=True, upload_to='payment_screenshots/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
