# Generated by Django 5.2.14 on 2026-05-28 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manual_sold_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_sold_item', to='market.order'),
        ),
    ]
